### ISSUE TITLE
Could not find a version that satisfies the requirement gym_xarm

### ISSUE THREAD

**Issue by CJ0510** [jc-bao/tianshou-bullet#1]
你好，请问如何解决

**Comment by jc-bao** [comment]
Hi, thank you for bringing this to our attention. I appreciate your interest in our project.

Regarding the dependency issue, I recommend installing the repository you mentioned, https://github.com/jc-bao/gym-xarm, to resolve it.

Additionally, I'd like to inform you that the original purpose of this repository was to implement hindsight experience replay. However, since the `tianshou` official repository now supports this feature, we have decided to no longer maintain this repository.

**Comment by CJ0510** [comment]
Thanks



---Original---
From: "Chaoyi ***@***.***&gt;
Date: Fri, Sep 8, 2023 20:15 PM
To: ***@***.***&gt;;
Cc: "Jing ***@***.******@***.***&gt;;
Subject: Re: [jc-bao/tianshou-bullet] Could not find a version that satisfiesthe requirement gym_xarm (Issue #1)




 
Hi, thank you for bringing this to our attention. I appreciate your interest in our project.
 
Regarding the dependency issue, I recommend installing the repository you mentioned, https://github.com/jc-bao/gym-xarm, to resolve it.
 
Additionally, I'd like to inform you that the original purpose of this repository was to implement hindsight experience replay. However, since the tianshou official repository now supports this feature, we have decided to no longer maintain this repository.
